### PR TITLE
Build with -Wextra

### PR DESCRIPTION
**Pull request by rojer**
Fix compile errors in current codebase - mainly unused arguments.

Some ObjC headers in XCode have unused arguments, so those need to be excepted.

### CODE REVIEW

**Comment by aajain-com** [comment]
Thanks @rojer for the change. Will review shortly and get back to you.

**Comment by rojer** [comment]
rebased onto latest master.
pint @aajain-com

**Comment by aajain-com** [comment]
@rojer the only reason I haven't merged it in is because I think it would be beneficial to have a working CI that can catch issues since we are enabling more warnings. I am pushing on our end to get that setup. If I don't make any headway in a day or two, I will merge your change. Thanks for your patience.

**Comment by rojer** [comment]
ok, no problem! i just want to minimize divergence in my fork.

**Comment by rojer** [comment]
@aajain-com how about now?

**Comment by aajain-com** [comment]
@rojer sorry for the delay. We do now have a working CI so I guess we can review your change and merge it. @carol-l-yang can you please review and approve?

**Review by carol-l-yang — APPROVED** [review]

**Review by carol-l-yang — APPROVED** [review]

**Pull request merged**
