### PR TITLE
Added support for televisions

### PR DESCRIPTION
**Pull request by johnathana**

### CODE REVIEW

**Review by ModestGoblin — APPROVED** [review]

**Comment by johnathana** [comment]
@ModestGoblin Thank you for your review. Rebased to current master HEAD. I don't get the mention from another repo.

**Comment by ModestGoblin** [comment]
> @ModestGoblin Thank you for your review. Rebased to current master HEAD. I don't get the mention from another repo.

Perspective @johnathana ... you dismissed my code review...

**Comment by johnathana** [comment]
@ModestGoblin Next steps?

**Comment by johnathana** [comment]
@ModestGoblin Do you expect something from my side? You didn't left any comments. I could not resolve the merge conflicts without _dismissing_ your review. 

@carol-l-yang @aajain-com @pgravel-com Could someone please review my PR? I will be very glad to follow your suggestions. I do not understand why someone is trying to insult my intentions.

**Comment by johnathana** [comment]
Closing due to inactivity.

**Comment by aajain-com** [comment]
Television accessory is an invitation only HomeKit program so please go through MFi portal for Television HomeKit accessory.

**Pull request closed without merging**
