### PR TITLE
Doxygen documentation generation

### PR DESCRIPTION
**Pull request by Clovel**
This MR is an example of what can be done. We must discuss if we want such documentation generation (#38).

### CODE REVIEW

**Comment by Clovel** [comment]
This MR is an example of what could be done for #38.

**Comment by Clovel** [comment]
Any news on this @aajain-com ?

**Comment by Clovel** [comment]
> Sorry I haven't take a look but this is next on my things to try. I don't see any where if you are limiting the doc generation to a specific directory or a file. I feel there is less value in generating doc for all of ADK and we should limit it to PAL APIs mostly.

That is possible. I will look into it.

**Comment by aajain-com** [comment]
Also, https://exhale.readthedocs.io/en/latest/#exhale-version-compatibility-with-python-sphinx-and-breathe seems promising.

Sphinx seems to generate much better output than doxygen. I am going to play around with it and let you know how it goes.

**Comment by aajain-com** [comment]
I have this working, will send a pull request shortly.

**Comment by aajain-com** [comment]
Replaced by https://github.com/apple/HomeKitADK/pull/48

**Pull request closed without merging**
